---
title: "About"
subtitle: "a bit more about me"
about:
  template: marquee
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com
    - icon: github
      text: Github
      href: https://github.com
---

Nice to meet you! My name is Simone Brazzi. I am 34 years old guy from Bologna, Italy.

I decided to open this blog as a personal journal (what a new idea! Who ever thought about this?) of my data journey. This also means it is an opportunity to display my portfolio and shares my projects.

At the date of writing, I am a self made data professional. I am currently working as a Data Scientist for UniCredit Group.

I have too many hobbies, but I will try to summarize them in a sparse order:

-   Training: my 2024 goal is to be able to run at least an half marathon.

-   Study: I am studying data science to further improve my knowledge in the data field. I would like to do a Master Degree in the field, but it is difficult to combine the private life with an international MSc, at least for now.

-   Gaming, movies and manga: of course! I mean, it is part of being a nerd, right?! For cliche purpose, I love Quentin Tarantino blabbering, Nolan craziness, even though my favorite genre is horror. My favorites directors are Jordan Pelee and Ari Aster. I am currently reading Berserker, My Hero Academia, Jujutsu Kaisen, One Piece, Chainsaw Man and Kagurabachi.

-   Cooking, I think it is in my vein being italian (joking!) and considering my mother is a chef.

For now, I think I have annoyed you enough: stay tuned for future posts!
